### ISSUE TITLE
After running driver I get Critical Structure Corruption after some time

### ISSUE THREAD

**Issue by CycloneRing** [dennisbabkin/InjectAll#4]
BSOD Critical Structure Corruption happens in CI.dll after 30 40 minutes

**Comment by dennisbabkin** [comment]
You'll need to collect the crash dump and see what caused it.

**Comment by CycloneRing** [comment]
> You'll need to collect the crash dump and see what caused it.

Thanks for reply, I fixed it, It was a bug in unloading routine of driver.

**Comment by volehuy1998** [comment]
Hi @CycloneRing,

I know you just fixed, but I really want to know that problem because I'm student learning driver programming, I need some cases to know about driver error.

So can you share your prolem and your solution to fix it?
