### ISSUE TITLE
Failed to allocate memory

### ISSUE THREAD

**Issue by Interrupt101** [dennisbabkin/InjectAll#5]
//Alloc memory
DLL_STATS* pDStats = (DLL_STATS*)ExAllocatePool2(ALLOC_TYPE_OnLoadImage, sizeof(DLL_STATS), TAG('kDSm'));

Since ExAllocatePoolWithTag is deprecated, i use ExAllocatePool2 now, but it failed to allocate memory.

**Comment by dennisbabkin** [comment]
Correct. `ExAllocatePool2` has a different encoding for its flags. You can replace it with:

    DLL_STATS* pDStats = (DLL_STATS*)ExAllocatePool2(POOL_FLAG_PAGED, sizeof(DLL_STATS), TAG('kDSm');
